---
abstract: 'Cache::Memcached::Fast bindings for Sledge::Cache'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  Sledge;:Exceptions: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Cache-Memcached-Fast
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Memcached::Fast: 0.1
  Sledge::Cache: 0.04
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
